#microservice name
spring.application.name=customer-service

#server config
server.port=8081

#data_source config
spring.datasource.url=jdbc:h2:mem:customer_service_db
spring.datasource.username=sa
spring.datasource.password=

#h2 config
spring.h2.console.enabled=true
spring.h2.console.path=/h2

#hibernate config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

#discovery client config
#spring.cloud.discovery.enabled=false
#par default c'est true parce que on a créé discovery

#config client config
spring.cloud.config.enabled=false


#tant que on a changer l'adress du discovery service alors on doit explictement declarer lurl

eureka.client.service-url.defaultZone=http://localhost:8899/eureka/



